# Generated by Django 6.0.3 on 2026-04-06 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "registration_no",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("dob", models.DateField()),
                ("age", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="FamilyDonationInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("father_blood_group", models.CharField(max_length=5)),
                ("mother_blood_group", models.CharField(max_length=5)),
                ("last_donation_date", models.DateField(blank=True, null=True)),
                (
                    "donor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="donors.donor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blood_group", models.CharField(max_length=5)),
                (
                    "donor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="donors.donor"
                    ),
                ),
            ],
        ),
    ]
