# Generated by Django 6.0.3 on 2026-04-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalinfo",
            name="medical_conditions",
            field=models.TextField(
                blank=True, help_text="Enter any diseases or medical history", null=True
            ),
        ),
    ]
