# Generated by Django 6.0.3 on 2026-04-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donors", "0002_medicalinfo_medical_conditions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donor",
            name="registration_no",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
