# Generated by Django 6.0.3 on 2026-04-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donors", "0003_alter_donor_registration_no"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="donor",
            table="donor_info",
        ),
        migrations.AlterModelTable(
            name="familydonationinfo",
            table="family_info",
        ),
    ]
